"""Load training JSON artifacts generated by ingest_answers.py."""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

TRAINING_DIR = Path(__file__).resolve().parents[2] / "training"

PART_FILES = {
    "part01": "part01_onboarding.json",
    "part02": "part02_main_chat.json",
    "part03": "part03_challenge.json",
    "part04": "part04_reasoning.json",
    "part05": "part05_high_stakes.json",
    "part06": "part06_chip_explanations.json",
    "part07": "part07_extended_qa.json",
    "journey": "mba_journey.json",
}


@lru_cache(maxsize=16)
def load_artifact(key: str) -> dict[str, Any]:
    filename = PART_FILES.get(key, key)
    path = TRAINING_DIR / filename
    if not path.is_file():
        raise FileNotFoundError(
            f"Training file not found: {path}. Run scripts/ingest_answers.py first."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def load_corpus_digest() -> str:
    path = TRAINING_DIR / "corpus_digest.txt"
    if not path.is_file():
        raise FileNotFoundError(f"Missing {path}")
    return path.read_text(encoding="utf-8")


def chip_explanation_lookup() -> dict[str, str]:
    """Map normalized sentence -> explanation from Part 6 goldens."""
    data = load_artifact("part06")
    out: dict[str, str] = {}
    for entry in data.get("chip_explanations", []):
        norm = " ".join(entry["sentence"].lower().split())
        out[norm] = entry["explanation"]
    return out


def enrich_claims_with_explanations(claims: list[dict[str, Any]]) -> list[dict[str, Any]]:
    lookup = chip_explanation_lookup()
    enriched = []
    for c in claims:
        norm = " ".join(c["sentence"].lower().split())
        copy = dict(c)
        if not copy.get("explanation") and norm in lookup:
            copy["explanation"] = lookup[norm]
        enriched.append(copy)
    return enriched
